# Generated by Django 4.0.5 on 2022-07-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile_no',
            field=models.CharField(max_length=11),
        ),
    ]
