# Generated by Django 4.0.5 on 2022-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_account_mobile_no_account_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.BigIntegerField(max_length=11),
        ),
    ]
