# Generated by Django 4.0.5 on 2022-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_account_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
