# Generated by Django 4.0.5 on 2022-07-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_pics/'),
        ),
    ]
