# Generated by Django 4.0.5 on 2022-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_account_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(default='Enter Your Address.', max_length=100),
        ),
    ]
