# Generated by Django 4.0.5 on 2022-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_account_is_worker_account2_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='ratings',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='working_fields',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Account2',
        ),
    ]
